### PR TITLE
⚡  Support for webpack 3

### LINKED ISSUE #18: Support webpack 3

### PR DESCRIPTION
**Pull request by michalkvasnicak**
Closes #18 

Available under dist-tag `webpack3` (`yarn add --dev spust@webpack3`)

Wait for:
* [ ] - webpack-contrib/extract-text-webpack-plugin#540

### CODE REVIEW

**Comment by michalkvasnicak** [comment]
Tested on big project. Everything ok except deprecation message from `extract-text-webpack-plugin`, but it isn't causing troubles to compile a bundle.

However I haven't found much difference in outputted bundle size.

**Comment by michalkvasnicak** [comment]
### Webpack 2.6.1
pasted image at 2017_06_20 19_09

### Webpack 3.0.0
image

**Comment by joshwiens** [comment]
@michalkvasnicak - `extract-text-webpack-plugin@3.0.0-rc.1` will be published in about 30 minutes which amongst other things, gets rid of the last remaining deprecated function.

**Comment by michalkvasnicak** [comment]
@d3viant0ne Thank you for information 😉

**Pull request closed without merging**
